SELECT a.IDAtracacao,
                                CDTUP,
                                IDBerco,
                                `Berço`,
                                `Porto Atracação`,
                                `Apelido Instalação Portuária`,
                                `Complexo Portuário`,
                                `Tipo da Autoridade Portuária`,
                                `Data Atracação`,
                                `Data Chegada`,
                                `Data Desatracação`,
                                `Data Início Operação`,
                                `Data Término Operação`,
                                DATE_FORMAT(a.`Data Início Operação`, 'MM') AS `Ano da data de início da operação`,
                                DATE_FORMAT(a.`Data Início Operação`, 'yyyy') AS `Mês da data de início da operação`,
                                `Tipo de Operação`,
                                `Tipo de Navegação da Atracação`,
                                `Nacionalidade do Armador`,
                                FlagMCOperacaoAtracacao,
                                Terminal,
                                `Município`,
                                UF,
                                SGUF,
                                `Região Geográfica`,
                                `Nº da Capitania`,
                                `Nº do IMO`, 
                                TEsperaAtracacao,
                                TEsperaInicioOp,
                                TOperacao,
                                TEsperaDesatracacao,
                                TAtracado,
                                TEstadia           
                        from Atracacao a INNER JOIN TemposAtracacao b ON (a.IDAtracacao = b.IDAtracacao)
                               WHERE a.`Data Atracação` IS NOT NULL